language: java
dist: trusty

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

cache:
  directories:
    - "${HOME}/.m2/"

install: true

before_script:
    - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"

script:
    - mvn clean test
